[book]
authors = ["don Miguel Ruiz Jr."]
language = "zh"
multilingual = false
src = "src"
title = "觉察真我"

[output.html]

[output.epub]
cover-image = "cover.jpg"
additional-css = ["src/epub.css"]
use-default-css = false
